<Project Sdk="MSTest.Sdk/4.0.2">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="MSTestSettings.fs" />
    <Compile Include="Test.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\StackedFlow\StackedFlow.fsproj" />
  </ItemGroup>

</Project>
